/**
 * GET /api/decisions?subjectId=X&limit=20
 *
 * Returns decision records scoped to the authenticated user's tenant.
 * - Non-admin: can only see decisions for their own tenant. If `subjectId` is
 *   provided, it's AND-scoped with the tenant filter (the caller cannot bypass
 *   tenant isolation by supplying an arbitrary subjectId).
 * - Admin: may pass `platformWide=true` to see all tenants (explicit; default
 *   is still own-tenant only).
 *
 * POST is intentionally ABSENT. Decision records are authored server-side by
 * the DecisionEngine via POST /api/state with `persist: true`. The client
 * cannot supply truthLevel, provenance, state, or computedAt — those are
 * authoritative fields generated by the engine (architecture §14, I6).
 */
import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireUserAuthenticated, canAccessTenant } from '@/lib/auth/guards';
import type { StateSnapshot, Provenance } from '@/kernel/primitives/types';

export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest) {
  const { user, response } = await requireUserAuthenticated();
  if (response) return response;

  const url = new URL(req.url);
  const requestedSubjectId = url.searchParams.get('subjectId');
  const limitParam = url.searchParams.get('limit');
  const platformWide = url.searchParams.get('platformWide') === 'true' && user.role === 'ADMIN';
  const limit = limitParam ? Math.min(200, Math.max(1, parseInt(limitParam, 10) || 20)) : 20;

  // Build the where clause. subjectId is AND-scoped with the tenant filter so
  // it can never be used to bypass tenant isolation.
  // Inline construction avoids intermediate variable type issues.
  const where: { tenantId?: string; subjectId?: string } = {};
  if (!platformWide && user.tenantId) {
    where.tenantId = user.tenantId;
  }
  if (requestedSubjectId) {
    where.subjectId = requestedSubjectId;
  }

  try {
    const records = await db.decisionRecord.findMany({
      where,
      orderBy: { computedAt: 'desc' },
      take: limit,
    });
    const decisions = records.map((r) => ({
      id: r.id,
      decisionId: r.decisionId,
      subjectId: r.subjectId,
      situationId: r.situationId,
      asOf: r.asOf,
      computedAt: r.computedAt,
      truthLevel: r.truthLevel,
      // Prisma's Json columns return already-parsed values (not strings).
      // Cast directly — do NOT call JSON.parse().
      state: r.stateJson as unknown as StateSnapshot,
      provenance: r.provenanceJson as unknown as Provenance[],
    }));
    return NextResponse.json({ decisions, count: decisions.length });
  } catch (err) {
    return NextResponse.json(
      { error: 'Failed to read decisions', detail: err instanceof Error ? err.message : 'unknown' },
      { status: 500 },
    );
  }
}

// POST handler intentionally does not exist.
// Decision records are created server-side by the DecisionEngine via
// POST /api/state with persist=true. The client cannot author decision
// records (truthLevel, provenance, state, computedAt are authoritative fields).
