/**
 * POST /api/state
 * The primary endpoint — runs the full DecisionEngine pipeline:
 *   ContextBuilder → RuleEngine → StateEngine → ProvenanceBuilder → AuditLog
 * Returns the computed StateSnapshot, provenance chain, and audit events.
 *
 * DECISION INTEGRITY (ADR 0013):
 *   The client sends a DecisionRequest: { subjectId, asOf, situationId, facts,
 *   jurisdictionIds, objective }. The server runs the DecisionEngine and
 *   produces the authoritative DecisionRecord fields (truthLevel, provenance,
 *   state, computedAt). The client CANNOT supply these fields.
 *
 * FACT INGESTION CONTRACT (ADR 0017):
 *   API-supplied facts are UNTRUSTED INPUT. The server normalizes every
 *   submitted fact's `tenantId` to the authenticated session's tenantId.
 *
 * TRANSACTIONAL PERSISTENCE (ADR 0018):
 *   When `persist: true`, the DecisionRecord AND its durable AuditEvent are
 *   persisted via a SINGLE Prisma `$transaction`. Both writes use the
 *   transaction-bound client. If either write fails, the transaction rolls
 *   back — neither record exists. There is NO compensating DELETE logic.
 *
 *   The response explicitly reports:
 *     - persisted: false (or absent) — computed only, not persisted
 *     - persisted: true — both DecisionRecord AND AuditEvent committed atomically
 *     - HTTP 500 — computed but transaction failed (caller knows to retry)
 *
 *   A `correlationId` (the engine's `decisionId`) is stored on BOTH the
 *   DecisionRecord and the AuditEvent, providing an explicit bidirectional
 *   link between a decision and its audit trail.
 *
 * Deterministic modulo informational timestamps (I5, I6, I13).
 */
import { NextRequest, NextResponse } from 'next/server';
import { createPackageRegistry } from '@/packages/registry/PackageRegistry';
import { createDecisionEngine } from '@/intelligence/decision/DecisionEngine';
import { requireUserWithScope } from '@/lib/auth/guards';
import { sanitizeAuditPayload } from '@/lib/auth/audit';
import { db } from '@/lib/db';
import type { ContextRequest, Fact } from '@/kernel/primitives/types';

export const dynamic = 'force-dynamic';

interface StateRequestBody {
  subjectId: string;
  asOf: string;
  situationId?: string;
  facts: Fact[];
  jurisdictionIds: string[];
  objective?: string;
  persist?: boolean;
}

export async function POST(req: NextRequest) {
  const { user, response } = await requireUserWithScope(req);
  if (response) return response;

  let body: StateRequestBody;
  try {
    body = (await req.json()) as StateRequestBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  if (!body.subjectId || !body.asOf || !Array.isArray(body.facts) || !Array.isArray(body.jurisdictionIds)) {
    return NextResponse.json(
      { error: 'Missing required fields: subjectId, asOf, facts[], jurisdictionIds[]' },
      { status: 400 },
    );
  }

  const registry = createPackageRegistry();
  const decisionEngine = createDecisionEngine();

  // FACT NORMALIZATION (ADR 0017): API-supplied facts are untrusted input.
  const normalizedFacts: Fact[] = body.facts.map((f) => ({
    ...f,
    tenantId: user.tenantId,
    subjectId: body.subjectId,
  }));

  const contextRequest: ContextRequest = {
    subjectId: body.subjectId,
    asOf: body.asOf,
    situationId: body.situationId,
    facts: normalizedFacts,
    jurisdictionIds: body.jurisdictionIds,
    objective: body.objective,
    tenantId: user.tenantId,
  };

  const result = decisionEngine.decide(contextRequest, registry);

  // If persist=true AND rules fired, persist the decision + audit atomically.
  if (body.persist && result.state.firedEffects.length > 0) {
    // The correlationId links the DecisionRecord and the AuditEvent.
    // It is the engine's decisionId — a UUID generated by the DecisionEngine.
    const correlationId = result.state.provenance[0]?.decisionId ?? `dec_${crypto.randomUUID()}`;

    try {
      // ── TRANSACTION BOUNDARY ──────────────────────────────────────────
      // Both the DecisionRecord and the AuditEvent are created via the
      // transaction-bound client `tx`. If either write throws, Prisma
      // rolls back the entire transaction — neither record is committed.
      // There is NO compensating DELETE. This is a real DB transaction.
      // ──────────────────────────────────────────────────────────────────
      const decisionRecord = await db.$transaction(async (tx) => {
        // 1. Create the DecisionRecord.
        const record = await tx.decisionRecord.create({
          data: {
            decisionId: correlationId,
            subjectId: body.subjectId,
            situationId: body.situationId ?? null,
            stateJson: JSON.parse(JSON.stringify(result.state)) as object,
            provenanceJson: JSON.parse(JSON.stringify(result.provenance)) as object,
            asOf: new Date(body.asOf),
            computedAt: new Date(result.state.computedAt),
            truthLevel: result.state.truthLevel,
            tenantId: user.tenantId,
            correlationId,
          },
        });

        // 2. Create the durable AuditEvent in the SAME transaction.
        //    Uses `tx.auditEvent` — NOT the global `db.auditEvent`.
        //    The payload is sanitized before insertion.
        const sanitizedPayload = sanitizeAuditPayload({
          decisionRecordId: record.id,
          decisionId: correlationId,
          situationId: body.situationId ?? null,
          firedEffects: result.state.firedEffects.length,
          truthLevel: result.state.truthLevel,
        });

        await tx.auditEvent.create({
          data: {
            tenantId: user.tenantId,
            actor: user.email,
            action: 'decision.persist',
            subjectId: body.subjectId,
            severity: 'INFO',
            payloadJson: sanitizedPayload,
            correlationId, // explicit bidirectional link to the DecisionRecord
          },
        });

        return record;
      });
      // ── TRANSACTION COMMITTED ──────────────────────────────────────────
      // Both writes succeeded atomically. The caller can trust that the
      // decision AND its audit trail are durably persisted.
      // ──────────────────────────────────────────────────────────────────

      return NextResponse.json({
        state: result.state,
        provenance: result.provenance,
        audit: result.audit,
        persisted: true,
        decisionRecordId: decisionRecord.id,
        correlationId,
      });
    } catch (err) {
      // Transaction failed — BOTH writes rolled back. Neither the
      // DecisionRecord nor the AuditEvent exists in the DB.
      console.error('[state] transactional persistence failed:', err);
      return NextResponse.json(
        {
          error: 'Decision was computed but could not be persisted durably.',
          detail: err instanceof Error ? err.message : 'Transaction failed.',
          state: result.state,
          provenance: result.provenance,
          audit: result.audit,
          persisted: false,
        },
        { status: 500 },
      );
    }
  }

  // persist=false or no rules fired — return computed result without persisting.
  return NextResponse.json({
    state: result.state,
    provenance: result.provenance,
    audit: result.audit,
    persisted: false,
  });
}
